const fs = require('fs');

async function main() {
  const base = 'http://127.0.0.1:4000/api';
  const login = async (email) => {
    const res = await fetch(base + '/auth/login', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password: 'Demo@12345' })
    }).then(r => r.json());
    return res.token;
  };

  const adminToken = await login('admin@demo.com');
  const leadToken = await login('lead@demo.com');
  const reviewerToken = await login('reviewer@demo.com');
  const juryToken = await login('jury@demo.com');
  const viewerToken = await login('viewer@demo.com');

  const meAdmin = await fetch(base + '/auth/me?editionId=1', { headers: { Authorization: 'Bearer ' + adminToken, 'X-Edition-Id': '1' } }).then(r => r.json());
  const meLead = await fetch(base + '/auth/me?editionId=1', { headers: { Authorization: 'Bearer ' + leadToken, 'X-Edition-Id': '1' } }).then(r => r.json());
  const meReviewer = await fetch(base + '/auth/me?editionId=1', { headers: { Authorization: 'Bearer ' + reviewerToken, 'X-Edition-Id': '1' } }).then(r => r.json());
  const meJury = await fetch(base + '/auth/me?editionId=1', { headers: { Authorization: 'Bearer ' + juryToken, 'X-Edition-Id': '1' } }).then(r => r.json());
  const meViewer = await fetch(base + '/auth/me?editionId=1', { headers: { Authorization: 'Bearer ' + viewerToken, 'X-Edition-Id': '1' } }).then(r => r.json());

  const events = await fetch(base + '/events', { headers: { Authorization: 'Bearer ' + adminToken } }).then(r => r.json());
  const eventConfig = await fetch(base + '/events/1/config', { headers: { Authorization: 'Bearer ' + adminToken } }).then(r => r.json());
  const groups = await fetch(base + '/admin/groups', { headers: { Authorization: 'Bearer ' + adminToken, 'X-Edition-Id': '1' } }).then(r => r.json());
  const perms = await fetch(base + '/admin/permissions', { headers: { Authorization: 'Bearer ' + adminToken, 'X-Edition-Id': '1' } }).then(r => r.json());
  const users = await fetch(base + '/admin/users', { headers: { Authorization: 'Bearer ' + adminToken, 'X-Edition-Id': '1' } }).then(r => r.json());
  const subsAdmin = await fetch(base + '/submissions', { headers: { Authorization: 'Bearer ' + adminToken, 'X-Edition-Id': '1' } }).then(r => r.json());
  const subsReviewer = await fetch(base + '/submissions', { headers: { Authorization: 'Bearer ' + reviewerToken, 'X-Edition-Id': '1' } }).then(r => r.json());
  const customA = await fetch(base + '/plugins/customA', { headers: { Authorization: 'Bearer ' + adminToken, 'X-Edition-Id': '2' } }).then(r => r.json());

  const lines = [
    '# Complete API Specification & Responses',
    '',
    'Comprehensive documentation of all live API endpoints and responses for the **Access Control System** on **https://access.saas.autovertest.com/api**.',
    '',
    '> [!IMPORTANT]',
    '> **Schema Changes Applied**:',
    '> 1. **`events` Table**: Uses `event_id` as primary key, with `user_id`, `name`, `description` (LONGTEXT), `event_type`, `saas_enabled`, and `is_deleted`.',
    '> 2. **`modules` Table**: Uses `label` alongside `name`. Obsolete `component_name` and `config` are removed.',
    '> 3. **`permissions` Table**: Uses `label` alongside `name`, foreign key `module_id`, `page_id`, `actions_match`, and `actions_unmatch`. Obsolete `resource`, `action`, and `scope` columns have been removed.',
    '> 4. **`module_groups` & `module_groups_permissions`**: Replaced legacy `group_permissions`. Permissions are scoped per-module per-group.',
    '> 5. **Scope Filtering Removed**: As decided by management, `scope_key` and `scope_id` are completely excluded for Phase 1. All users with permission to view submissions see all submissions (`activeScope: \'all\'`).',
    '',
    '---',
    '',
    '## 1. Authentication & Identity Endpoints',
    '',
    '### 1.1 `POST /api/auth/login`',
    '',
    'Authenticates user credentials and returns an authentication JWT token plus user basic metadata. Also sets an `HttpOnly` secure cookie.',
    '',
    '#### Request',
    '```http',
    'POST /api/auth/login HTTP/1.1',
    'Content-Type: application/json',
    '',
    '{',
    '  "email": "admin@demo.com",',
    '  "password": "Demo@12345"',
    '}',
    '```',
    '',
    '#### Response (200 OK)',
    '```json',
    JSON.stringify({
      message: 'Login successful.',
      user: { id: 1, name: 'Admin User', email: 'admin@demo.com' },
      token: adminToken
    }, null, 2),
    '```',
    '',
    '---',
    '',
    '### 1.2 `GET /api/auth/me` — Current User Profile & Permissions',
    '',
    'Returns the user profile, event groups, current active group (`current_group`), and the **permissions map** for the active event context (passed via `X-Event-Id` or `X-Edition-Id` header).',
    '',
    '> [!NOTE]',
    '> All permissions are formatted in colon notation as `resource:action`. Each entry contains `description`, `page`, `elementId`, and UI `action: { match, unmatch }` read directly from the database. The wildcard `*` expands to all system permissions for Admin users (`"isSuperAdmin": true`). `scope_key` has been removed.',
    '',
    '---',
    '',
    '#### Persona 1: Administrator (`admin@demo.com`)',
    '**Header:** `X-Event-Id: 1`  ',
    '**Access Level:** Full Super Admin across all system permissions (`isSuperAdmin: true`).',
    '',
    '```json',
    JSON.stringify(meAdmin, null, 2),
    '```',
    '',
    '---',
    '',
    '#### Persona 2: Reviewer (`reviewer@demo.com`)',
    '**Header:** `X-Event-Id: 1`  ',
    '**Access Level:** Scoped to submissions intake and review workflows via module groups.',
    '',
    '```json',
    JSON.stringify(meReviewer, null, 2),
    '```',
    '',
    '---',
    '',
    '#### Persona 3: Jury Member (`jury@demo.com`)',
    '**Header:** `X-Event-Id: 1`  ',
    '**Access Level:** Scoped to jury panel evaluation and scoring.',
    '',
    '```json',
    JSON.stringify(meJury, null, 2),
    '```',
    '',
    '---',
    '',
    '#### Persona 4: Group Lead (`lead@demo.com`)',
    '**Header:** `X-Event-Id: 1`  ',
    '**Access Level:** Departmental workforce and operational tasks.',
    '',
    '```json',
    JSON.stringify(meLead, null, 2),
    '```',
    '',
    '---',
    '',
    '#### Persona 5: Volunteer (`viewer@demo.com`)',
    '**Header:** `X-Event-Id: 1`  ',
    '**Access Level:** Operational access to calendar and task checklist.',
    '',
    '```json',
    JSON.stringify(meViewer, null, 2),
    '```',
    '',
    '---',
    '',
    '### 1.3 `POST /api/auth/register`',
    '',
    'Registers a new user account in the system.',
    '',
    '#### Request',
    '```http',
    'POST /api/auth/register HTTP/1.1',
    'Content-Type: application/json',
    '',
    '{',
    '  "name": "Alice Taylor",',
    '  "email": "alice@example.com",',
    '  "password": "SecurePass123!"',
    '}',
    '```',
    '',
    '#### Response (200 OK)',
    '```json',
    JSON.stringify({ id: 7, name: 'Alice Taylor', email: 'alice@example.com' }, null, 2),
    '```',
    '',
    '---',
    '',
    '### 1.4 `POST /api/auth/logout`',
    '',
    'Invalidates the session and clears the `access-token` cookie.',
    '',
    '#### Response (200 OK)',
    '```json',
    JSON.stringify({ message: 'Logged out successfully.' }, null, 2),
    '```',
    '',
    '---',
    '',
    '## 2. Events & Editions Endpoints',
    '',
    '### 2.1 `GET /api/events`',
    '',
    'Returns all active events/festivals (`is_deleted = 0`). Notice the production schema attributes: `event_id`, `user_id`, `event_type`, `saas_enabled`, `is_deleted`.',
    '',
    '#### Response (200 OK)',
    '```json',
    JSON.stringify(events, null, 2),
    '```',
    '',
    '---',
    '',
    '### 2.2 `GET /api/events/:id/config`',
    '',
    'Returns full module and feature configuration for a specific event. Presence in `events_modules` dynamically sets `is_enabled: 1`. Notice `label` is included alongside `name`.',
    '',
    '#### Response (200 OK)',
    '```json',
    JSON.stringify(eventConfig, null, 2),
    '```',
    '',
    '---',
    '',
    '## 3. Administration Endpoints',
    '',
    '### 3.1 `GET /api/admin/groups` (Groups Management)',
    '',
    'Returns all permission groups along with their assigned module-group permissions and active member counts. Notice that `scope_key` is removed, and permissions contain `module_id`, `page_id`, `actions_match`, and `actions_unmatch`.',
    '',
    '#### Response (200 OK)',
    '```json',
    JSON.stringify(groups, null, 2),
    '```',
    '',
    '---',
    '',
    '### 3.2 `GET /api/admin/permissions`',
    '',
    'Returns the system-wide permission registry. Notice the columns: `label`, `module_id`, `page_id`, `actions_match`, and `actions_unmatch` (and no legacy `resource`/`action`/`scope`).',
    '',
    '#### Response (200 OK)',
    '```json',
    JSON.stringify(perms, null, 2),
    '```',
    '',
    '---',
    '',
    '### 3.3 `GET /api/admin/users`',
    '',
    'Returns all registered users with their assigned event groups.',
    '',
    '#### Response (200 OK)',
    '```json',
    JSON.stringify(users, null, 2),
    '```',
    '',
    '---',
    '',
    '## 4. Scoped Data & Functional Endpoints',
    '',
    '### 4.1 `GET /api/submissions` (Admin View vs Reviewer View)',
    '',
    '#### Admin View (`admin@demo.com`)',
    '```http',
    'GET /api/submissions HTTP/1.1',
    'Authorization: Bearer <ADMIN_TOKEN>',
    'X-Edition-Id: 1',
    '```',
    '',
    '#### Response (200 OK)',
    '```json',
    JSON.stringify(subsAdmin, null, 2),
    '```',
    '',
    '#### Reviewer View (`reviewer@demo.com`)',
    '```http',
    'GET /api/submissions HTTP/1.1',
    'Authorization: Bearer <REVIEWER_TOKEN>',
    'X-Edition-Id: 1',
    '```',
    '',
    '#### Response (200 OK)',
    '```json',
    JSON.stringify(subsReviewer, null, 2),
    '```',
    '',
    '> [!NOTE]',
    '> Following the managerial decision, `scope_key` (row-level data filtering) has been removed for Phase 1. All users with `submission:view` / `submission:read` permission see all active submissions for that event with `"activeScope": "all"`.',
    '',
    '---',
    '',
    '### 4.2 `GET /api/plugins/customA` (Zero-Code Custom Plugin)',
    '',
    'Demonstrates data returned from custom dynamically loaded plugins when enabled for an event (`X-Edition-Id: 2`).',
    '',
    '#### Response (200 OK)',
    '```json',
    JSON.stringify(customA, null, 2),
    '```',
    ''
  ];

  const targetPath = '/root/.gemini/antigravity-ide/brain/9fc7ccc2-27b4-45bf-9e03-08b481298897/api_responses.md';
  fs.writeFileSync(targetPath, lines.join('\n'));
  console.log('Successfully wrote api_responses.md to ' + targetPath);
}

main().catch(err => {
  console.error('Error generating api_responses.md:', err);
  process.exit(1);
});
